name: Publish to NPM

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Build with pkgroll
      run: npm run build

  publish-npm:
    needs: build
    environment: 
      name: npm-publish
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
    - name: Publish to NPM
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
